# エラー
class UserAlreadyExistsError(Exception):
    """すでに同一の user_id が存在する場合の例外"""
    pass